parameters:
    ping_localhost.anonymizer_bundle.default_locale: 'nl_NL'

services:
    PingLocalhost\AnonymizerBundle\Driver\AnonymizeDriver:
        class: 'PingLocalhost\AnonymizerBundle\Driver\AnonymizeDriver'
        arguments:
          - '@Doctrine\Common\Annotations\AnnotationReader'
          - '%ping_localhost.anonymizer_bundle.default_locale%'

    Metadata\MetadataFactory:
        class: 'Metadata\MetadataFactory'
        arguments:
          - '@PingLocalhost\AnonymizerBundle\Driver\AnonymizeDriver'

    PingLocalhost\AnonymizerBundle\Processor\AnonymizeProcessor:
        class: 'PingLocalhost\AnonymizerBundle\Processor\AnonymizeProcessor'
        arguments:
          - '@Metadata\MetadataFactory'

    Doctrine\Common\Annotations\AnnotationReader:
        class: 'Doctrine\Common\Annotations\AnnotationReader'
